### ISSUE TITLE
Blocker: Email not being sent from contact form

### ISSUE THREAD

**Issue by joebachana** [DrupalCamp-NYC/dcnyc16#21]
http://dev-drupalcampnyc.pantheon.io/contact

**Comment by FatherShawn** [comment]
@joebachana I just added myself for the moment as a second recipient.  I received the message:

[contact-us-test.txt](https://github.com/DrupalCamp-NYC/dcnyc16/files/78931/contact-us-test.txt)

**Comment by joebachana** [comment]
given that Shawn gets the email and I don't, we'll assume this is an issue w/ my host provider so I'll mark this as closed then open another ticket for me to swap a separate email after launch. This might inconvenience Shawn slightly for a few days in having to forward me any emails from people contacting us...
