### ISSUE TITLE
footer quite close to bottom of main content (Premium sponsor block)

### ISSUE THREAD

**Issue by joebachana** [DrupalCamp-NYC/dcnyc16#27]
Trying to think about the easiest way to resolve this since they're overlapping. The thoughts are:

1. Just eliminate the "connect with us" block since its abutting too closely
2. Make the "Powered by Drupal 8" smaller
3. Make the Pantheon logo smaller

Or,

Simply drop a horizontal rule between content and footer to set a visual demarcation. This suggestion might include some of the above.

This is NOT a blocker to site launch, it is a nice-to-have that hopefully Tim can help address.

**Comment by FatherShawn** [comment]
This was fixed but not yet updated on test.  updated now:
![footer-spacing](https://cloud.githubusercontent.com/assets/414635/12123243/d6479d10-b3ad-11e5-8f39-c59cff077f90.png)
