### ISSUE TITLE
Place CTA buttons side by side not stacked ("register" should be on the left)

### ISSUE THREAD

**Issue by joebachana** [DrupalCamp-NYC/dcnyc16#32]
Would be preferable to have them side by side so as not to push other content below the fold. Not a blocker, this is a 'nice to have.'

**Comment by hhilaire** [comment]
The content is far down also because there is a big margin top (50px) on the main content. Would you like me to reduce it ?

**Comment by joebachana** [comment]
yes please reduce the margin to an acceptable depth

**Comment by joebachana** [comment]
Fixed
