### ISSUE TITLE
D8 bug?: menu items lose their order

### ISSUE THREAD

**Issue by joebachana** [DrupalCamp-NYC/dcnyc16#40]
strange behavior in parent navigation - the menu items lose their order. I have seen this on another D8 implementation, haven't had time to figure out what is going on. Need to work through this, I'll try manually setting the weight of the items to see if that helps resolve this.

**Comment by joebachana** [comment]
interesting conundrum on this. menu order seems to be in code, however weighting is with the node. thoughts Shawn? I would update the weighting on the live site to address this issue, although that doesn't explain the behavior of menu item reordering using menu interface in administration

**Comment by joebachana** [comment]
further inspection, the issue is the sponsor page view - there's no way (that i know of) to assign weighting to a view, so that one keeps getting pushed to the end of the menu. this is new behavior in D8. thoughts?

**Comment by FatherShawn** [comment]
So does re-ordering at `/admin/structure/menu` not work?  If it does we just need to get that captured.

**Comment by joebachana** [comment]
reordering does not appear to work wrt the page view, but i haven't had time to reliably reproduce it. it has happened several times now. reordering nodes in /admin/structure/menu seems to work. I tried to manually weight the sponsor view (so we'll see if that helps) but the drag/drop fails to hold up.
