### ISSUE TITLE
decrease point size of Head (Drupalcampnyc2016 or address in mobile space

### ISSUE THREAD

**Issue by joebachana** [DrupalCamp-NYC/dcnyc16#50]
the home page head wraps to two lines - needs to be addressed - Helene no rush on this but please address it when you get a moment

**Comment by joebachana** [comment]
any update on this Helene? Again, no rush but would be good just to clean this minor tidbit up

**Comment by hhilaire** [comment]
Didn't have a moment to work on it, this week should be good

**Comment by hhilaire** [comment]
FIxed the issue and created a pull request.
