### ISSUE TITLE
Where to host site?

### ISSUE THREAD

**Issue by joebachana** [DrupalCamp-NYC/dcnyc16#9]
we own drupalcamp.nyc, currently pointing to Amy Cham's server, but she expresses a preference for us to deploy this site elsewhere. Thoughts on where we can put this?

**Comment by FatherShawn** [comment]
Pantheon gives free camp hosting for a footer link: https://pantheon.io/free-website-management-platform-beyond-hosting

**Comment by joebachana** [comment]
never used Pantheon, once the site is deployed there, I can create/edit nodes as normal, or have to go through Git or some other 'pantheonic' process to do so? If same as any other drupal site I say lets go for it, although I don't know the contact info of the person there to make this happen.

**Comment by FatherShawn** [comment]
Site function should be normal or it is not a Drupal site!
